-- ╭──────────────────────────────────────────────────────────╮
-- │          Copyright (c) 2022-present Lalit Kumar          │
-- │                       License: MIT                       │
-- ╰──────────────────────────────────────────────────────────╯

require("cobalt2/plugins/barbar")
require("cobalt2/plugins/bufferline")
require("cobalt2/plugins/coc")
require("cobalt2/plugins/fidget")
require("cobalt2/plugins/gitgutter")
require("cobalt2/plugins/gitsigns")
require("cobalt2/plugins/hop")
require("cobalt2/plugins/indent-blankline")
require("cobalt2/plugins/leap")
require("cobalt2/plugins/lightspeed")
require("cobalt2/plugins/lir")
require("cobalt2/plugins/marks")
require("cobalt2/plugins/neo-tree")
require("cobalt2/plugins/neogit")
require("cobalt2/plugins/notify")
require("cobalt2/plugins/nvim-cmp")
require("cobalt2/plugins/nvim-hlslens")
require("cobalt2/plugins/nvim-lsp")
require("cobalt2/plugins/nvim-lsp-installer")
require("cobalt2/plugins/nvim-tree")
require("cobalt2/plugins/nvim-treesitter")
require("cobalt2/plugins/nvim-ts-rainbow")
require("cobalt2/plugins/package-info")
require("cobalt2/plugins/packer")
require("cobalt2/plugins/startify")
require("cobalt2/plugins/telescope")
require("cobalt2/plugins/trouble")
require("cobalt2/plugins/which-key")
