-- ╭──────────────────────────────────────────────────────────╮
-- │          Copyright (c) 2022-present Lalit Kumar          │
-- │                       License: MIT                       │
-- ╰──────────────────────────────────────────────────────────╯

require("cobalt2/plugins/barbar")
require("cobalt2/plugins/barbecue")
require("cobalt2/plugins/blink-cmp")
require("cobalt2/plugins/bqf")
require("cobalt2/plugins/bufferline")
require("cobalt2/plugins/coc")
require("cobalt2/plugins/copilot")
require("cobalt2/plugins/dashboard")
require("cobalt2/plugins/diffview")
require("cobalt2/plugins/eyeliner")
require("cobalt2/plugins/fidget")
require("cobalt2/plugins/flash")
require("cobalt2/plugins/fzf-lua")
require("cobalt2/plugins/gitgutter")
require("cobalt2/plugins/gitsigns")
require("cobalt2/plugins/hop")
require("cobalt2/plugins/indent-blankline")
require("cobalt2/plugins/indentmini")
require("cobalt2/plugins/leap")
require("cobalt2/plugins/lightspeed")
require("cobalt2/plugins/lir")
require("cobalt2/plugins/lualine")
require("cobalt2/plugins/marks")
require("cobalt2/plugins/neo-tree")
require("cobalt2/plugins/neogit")
require("cobalt2/plugins/noice")
require("cobalt2/plugins/notify")
require("cobalt2/plugins/nvim-cmp")
require("cobalt2/plugins/nvim-fFHighlight")
require("cobalt2/plugins/nvim-hlslens")
require("cobalt2/plugins/nvim-lsp")
require("cobalt2/plugins/nvim-navic")
require("cobalt2/plugins/nvim-tree")
require("cobalt2/plugins/nvim-treesitter")
require("cobalt2/plugins/nvim-ts-rainbow")
require("cobalt2/plugins/octo")
require("cobalt2/plugins/package-info")
require("cobalt2/plugins/packer")
require("cobalt2/plugins/quick-scope")
require("cobalt2/plugins/reach")
require("cobalt2/plugins/render-markdown")
require("cobalt2/plugins/startify")
require("cobalt2/plugins/symbols-outline")
require("cobalt2/plugins/telescope")
require("cobalt2/plugins/trouble")
require("cobalt2/plugins/which-key")
require("cobalt2/plugins/yanky")
