local colors = require("cobalt2.utils").colors
local styles = require("cobalt2.utils").styles
local Group = require("cobalt2.utils").Group

Group.new("TSAnnotation", colors.yellow, nil, nil)
Group.new("TSAttribute", colors.yellow, nil, nil)
Group.new("TSBoolean", colors.dark_pink, nil, styles.italic)
Group.new("TSCharacter", colors.dark_pink, nil, nil)
Group.new("TSConditional", colors.dark_orange, nil, nil)
Group.new("TSConstBuiltin", colors.dark_pink, nil, styles.italic)
Group.new("TSConstMacro", colors.light_blue, nil, nil)
Group.new("TSConstant", colors.white, nil, nil)
Group.new("TSConstructor", colors.light_green, nil, nil)
Group.new("TSEmphasis", colors.white, nil, styles.italic)
Group.new("TSError", colors.red:light(), nil, nil)
Group.new("TSException", colors.pink, nil, nil)
Group.new("TSField", colors.white, nil, nil)
Group.new("TSFloat", colors.dark_pink, nil, nil)
Group.new("TSFuncBuiltin", colors.dark_orange, nil, nil)
Group.new("TSFuncMacro", colors.light_orange, nil, nil)
Group.new("TSFunction", colors.dark_orange, nil, nil)
Group.new("TSInclude", colors.dark_orange, nil, styles.italic)
Group.new("TSKeyword", colors.dark_orange, nil, styles.italic)
Group.new("TSKeywordFunction", colors.light_pink, nil, styles.bold + styles.italic)
Group.new("TSKeywordOperator", colors.yellow, nil, nil)
Group.new("TSLabel", colors.yellow, nil, nil)
Group.new("TSLiteral", colors.light_green, nil, nil)
Group.new("TSMethod", colors.yellow, nil, nil)
Group.new("TSNamespace", colors.white, nil, styles.italic)
Group.new("TSNumber", colors.dark_pink, nil, nil)
Group.new("TSOperator", colors.yellow, nil, nil)
Group.new("TSParameter", colors.light_orange, nil, nil)
Group.new("TSParameterReference", colors.light_orange, nil, nil)
Group.new("TSProperty", colors.light_blue, nil, styles.italic)
Group.new("TSPunctBracket", colors.white, nil, nil)
Group.new("TSPunctDelimiter", colors.white, nil, nil)
Group.new("TSPunctSpecial", colors.dark_pink, nil, nil)
Group.new("TSRepeat", colors.dark_orange, nil, nil)
Group.new("TSString", colors.light_green, nil, nil)
Group.new("TSStringEscape", colors.light_green, nil, nil)
Group.new("TSStringRegex", colors.green, nil, nil)
Group.new("TSStringSpecial", colors.green, nil, styles.italic)
Group.new("TSStrong", colors.white, nil, styles.bold)
Group.new("TSStructure", colors.light_blue, nil, nil)
Group.new("TSTag", colors.yellow, nil, nil)
Group.new("TSTagDelimiter", colors.dirty_blue, nil, nil)
Group.new("TSText", colors.white, nil, nil)
Group.new("TSTitle", colors.yellow, nil, styles.bold)
Group.new("TSType", colors.yellow, nil, nil)
Group.new("TSTypeBuiltin", colors.yellow, nil, nil)
Group.new("TSURI", colors.light_blue, nil, styles.underline)
Group.new("TSUnderline", colors.white, nil, styles.underline)
Group.new("TSVariable", colors.white, nil, nil)
Group.new("TSVariableBuiltin", colors.yellow, nil, nil)

--------------------------------------------------------------------------------
--  treesitter-context
--------------------------------------------------------------------------------
Group.new("TreesitterContext", nil, colors.cursor_line, nil)
Group.new("TreesitterContextLineNumber", colors.blue, colors.cursor_line, nil)
