local Group = require("cobalt2/utils").Group
local colors = require("cobalt2/utils").colors

Group.new("ReachBorder", colors.blue, nil, nil)
Group.new("ReachCurrent", colors.yellow, nil, nil)
Group.new("ReachDirectory", colors.blue, nil, nil)
Group.new("ReachGrayOut", colors.light_grey, nil, nil)
Group.new("ReachHandleBuffer", colors.green, nil, nil)
Group.new("ReachHandleDelete", colors.red, nil, nil)
Group.new("ReachHandleMarkGlobal", colors.purple, nil, nil)
Group.new("ReachHandleMarkLocal", colors.dark_pink, nil, nil)
Group.new("ReachHandleSplit", colors.purple, nil, nil)
Group.new("ReachHandleTabpage", colors.yellow, nil, nil)
Group.new("ReachMark", colors.white, nil, nil)
Group.new("ReachMarkLocation", colors.blue, nil, nil)
Group.new("ReachMatchExact", colors.yellow, nil, nil)
Group.new("ReachModifiedIndicator", colors.red, nil, nil)
Group.new("ReachPriority", colors.dark_pink, nil, nil)
Group.new("ReachTail", colors.white, nil, nil)
