local Color, colors, Group, groups, styles = require('colorbuddy').setup()

Color.new('cobalt_bg', '#122637')
Color.new('black', '#1C1C1C')
Color.new('darkest_grey', '#3A3A3A')
Color.new('darker_grey', '#444444')
Color.new('dark_grey', '#626262')
Color.new('grey', '#808080')
Color.new('light_grey', '#9E9E9E')
Color.new('lighter_grey', '#BCBCBC')
Color.new('lightest_grey', '#CCCCCC')
Color.new('white', '#FFFFFF')

Color.new('dark_orange', '#FF9A00')
Color.new('light_orange', '#FF9D00')
Color.new('yellow', '#FFC600')
Color.new('light_yellow', '#F2ED7F')

Color.new('darkest_green', '#2D7067')
Color.new('dirty_green', '#70b950')
Color.new('green', '#3AD900')
Color.new('light_green', '#88FF88')
Color.new('lighter_green', '#9EFF80')
Color.new('lightest_green', '#BBFFDD')

Color.new('dark_purple', '#345FA8')
Color.new('purple', '#967EFB')
Color.new('light_purple', '#DEEBFE')

Color.new('darkest_blue', '#0000df')
Color.new('darker_blue', '#0050A4')
Color.new('dark_blue', '#0088FF')
Color.new('blue', '#00AAFF')
Color.new('light_blue', '#80FCFF')
Color.new('greyish_blue', '#8fbfdc')
Color.new('dirty_blue', '#668799')

Color.new('aubergine', '#4F0037')
Color.new('darker_red', '#700009')
Color.new('dark_red', '#902020')
Color.new('red', '#FF0000')
Color.new('dark_pink', '#FF628C')
Color.new('pink', '#FF00FF')
Color.new('light_pink', '#EE80E1')
Color.new('lightest_pink', '#FFA5F3')
Color.new('pale_pink', '#F0A0C0')
Color.new('dirty_pink', '#EB939A')

-- custom colors
Color.new('cursor_line', '#2a3c4b')

Group.new('Normal', p.white, p.cobalt_bg, nil)
Group.new('Comment', p.dark_blue, nil, styles.italic)
Group.new('Todo', p.dark_blue, nil, styles.bold)
Group.new('Constant', p.dark_pink, nil, styles.italic)
Group.new('Special', p.light_green, nil, nil)
Group.new('MoreMsg', p.light_green, nil, nil)
Group.new('Delimiter', p.dirty_blue, nil, nil)
Group.new('String', p.green, nil, nil)
Group.new('Identifier', p.dark_orange, nil, nil)
Group.new('Structure', p.dark_blue, nil, styles.italic)
Group.new('Function', p.yellow, nil, nil)
Group.new('Statement', p.dark_orange, nil, nil)
Group.new('PreProc', p.dark_orange, nil, nil)
Group.new('Operator', p.dark_blue, nil, styles.NONE)
Group.new('Type', p.yellow, nil, nil)
Group.new('NonText', p.dark_grey, p.cobalt_bg, nil)
Group.new('SpecialKey', p.darker_grey, p.black, nil)
Group.new('MatchParen', p.white, p.dark_purple, styles.bold)
Group.new('MatchWord', p.white, p.dark_purple, styles.bold)
Group.new('Directory', p.yellow, nil, nil)
Group.new('ErrorMsg', nil, p.dark_red, nil)
Group.new('Question', p.green, nil, nil)
Group.new('StorageClass', p.light_orange, nil, nil)
Group.new('TabLine', p.black, p.lighter_grey, styles.italic)
Group.new('TabLineFill', p.light_grey, nil, nil)
Group.new('TabLineSel', p.black, p.yellow, styles.bold)
Group.new('PMenu', p.lightest_grey, p.darkest_grey, nil)
Group.new('PMenuSel', p.darkest_grey, p.yellow, nil)
Group.new('PMenuSBar', nil, p.dark_grey, nil)
Group.new('PMenuThumb', nil, p.lightest_grey, nil)
Group.new('Visual', nil, p.darker_blue, nil)
Group.new('Cursor', p.yellow, p.cobalt_bg, nil)
Group.new('CursorColumn', nil, p.yellow, nil)
Group.new('CursorLine', nil, p.cursor_line, nil)
Group.new('CursorLineNr', p.yellow, nil, styles.bold)
Group.new('LineNr', p.blue, p.cobalt_bg, styles.NONE)
Group.new('StatusLine', p.black, p.lightest_grey, styles.italic)
Group.new('StatusLineNC', p.white, p.darker_grey, styles.italic)
Group.new('VertSplit', p.yellow, nil, nil)
Group.new('WildMenu', p.pale_pink, p.darkest_grey, nil)
Group.new('Folded', p.light_grey, p.darker_grey, styles.italic)
Group.new('FoldColumn', p.dark_grey, p.black, nil)
Group.new('SignColumn', p.cobalt_bg, nil, nil)
Group.new('ColorColumn', nil, p.black, nil)
Group.new('Title', p.dirty_green, nil, styles.bold)
Group.new('Search', p.dark_blue, p.greyish_blue, styles.underline)
Group.new('SpellBad', p.dark_red, nil, styles.underline)
Group.new('SpellCap', nil, p.darkest_blue, styles.underline)
Group.new('SpellRare', nil, p.aubergine, styles.underline)
Group.new('SpellLocal', nil, p.darkest_green, styles.underline)
Group.new('DiffDelete', p.black, p.darker_red, nil)
Group.new('DiffChange', nil, p.darkest_green, nil)
Group.new('DiffText', p.greyish_blue, p.black, nil)
Group.new('IndentBlankLineChar', p.grey, nil, nil)
Group.new('BufferCurrent', p.grey, p.cobalt_bg, nil)

---------------------------------------------------------------------------------
--                          plugins highlight groups                           --
---------------------------------------------------------------------------------

-- NOTE:  Neovim Treesitter:
Group.new('TSError', p.dark_red, nil, nil)
Group.new('TSPunctDelimiter', p.dirty_blue, nil, nil)
Group.new('TSPunctBracket', p.dirty_blue, nil, nil)
Group.new('TSPunctSpecial', p.dirty_blue, nil, nil)
-- Constant
Group.new('TSConstant', p.blue, nil, nil)
Group.new('TSConstBuiltin', p.light_green, nil, nil)
Group.new('TSConstMacro', p.light_blue, nil, nil)
Group.new('TSStringRegex', p.green, nil, nil)
Group.new('TSString', p.green, nil, nil)
Group.new('TSStringEscape', p.darker_red, nil, nil)
Group.new('TSCharacter', p.dark_red, nil, nil)
Group.new('TSNumber', p.light_pink, nil, nil)
Group.new('TSBoolean', p.light_pink, nil, nil)
Group.new('TSFloat', p.red, nil, nil)
Group.new('TSAnnotation', p.yellow, nil, nil)
Group.new('TSAttribute', p.yellow, nil, nil)
Group.new('TSNamespace', p.light_blue, nil, styles.italic)
-- Functions
Group.new('TSFuncBuiltin', p.light_green, nil, nil)
Group.new('TSFunction', p.yellow, nil, nil)
Group.new('TSFuncMacro', p.light_orange, nil, nil)
Group.new('TSParameter', p.light_orange, nil, nil)
Group.new('TSParameterReference', p.light_orange, nil, nil)
Group.new('TSMethod', p.yellow, nil, nil)
Group.new('TSField', p.light_orange, nil, nil)
Group.new('TSProperty', p.light_orange, nil, nil)
Group.new('TSConstructor', p.light_green, nil, nil)
-- Keywords
Group.new('TSConditional', p.red, nil, nil)
Group.new('TSRepeat', p.red, nil, nil)
Group.new('TSLabel', p.yellow, nil, nil)
Group.new('TSKeyword', p.yellow, nil, styles.italic)
Group.new('TSKeywordFunction', p.light_pink, nil, styles.italic)
Group.new('TSKeywordOperator', p.yellow, nil, nil)
Group.new('TSOperator', p.yellow, nil, nil)
Group.new('TSException', p.pink, nil, nil)
Group.new('TSType', p.yellow, nil, nil)
Group.new('TSTypeBuiltin', p.yellow, nil, nil)
Group.new('TSStructure', p.light_blue, nil, nil)
Group.new('TSInclude', p.light_blue, nil, nil)
-- Variable
Group.new('TSVariable', p.white, nil, nil)
Group.new('TSVariableBuiltin', p.yellow, nil, nil)
-- Text
Group.new('TSText', p.white, nil, nil)
Group.new('TSStrong', p.white, nil, nil)
Group.new('TSEmphasis', p.white, nil, nil)
Group.new('TSUnderline', p.white, nil, styles.underline)
Group.new('TSTitle', p.dirty_green, nil, nil)
Group.new('TSLiteral', p.green, nil, nil)
Group.new('TSURI', p.greyish_blue, nil, styles.underline)
-- Tags
Group.new('TSTag', p.yellow, nil, nil)
Group.new('TSTagDelimiter', p.dirty_blue, nil, nil)
